In [7]:
import numpy as np
a1 = np.array([1,2,3,4,5])
print(a1)


[1 2 3 4 5]


In [24]:
import numpy as np
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])
add = a + b
print("sum = ",add)

sub = a - b
print("Subtract = ",sub)

mul = a * b
print("Multiplication = ",mul)

div = a / b
print("Division = ",div)

sum =  [5 7 9]
Subtract =  [-3 -3 -3]
Multiplication =  [ 4 10 18]
Division =  [0.25 0.4  0.5 ]


In [2]:
import numpy as np
c = np.array([2,2,3])
result = 5+c
print("Result:",result)

Result: [7 7 8]


In [3]:
c = np.array([1,2,3,4,5,6])
result = c**2
print(result)

[ 1  4  9 16 25 36]


In [4]:
a1 = np.array([2,3,4,5,6])
sq_arr = np.square(a1)
print("square array: ",sq_arr)

square array:  [ 4  9 16 25 36]


In [7]:
a1 = np.array([4,9,64])
sq_rt = np.sqrt(a1)
print("square roots ",sq_rt)

square roots  [2. 3. 8.]


In [4]:
import numpy as np
a1 = np.array([1,2,3])
exp_arr = np.exp(a1)
print("Exponents :",exp_arr)

Exponents : [ 2.71828183  7.3890561  20.08553692]


In [5]:
sum_arr = np.sum(a1)
print("Sum:",sum_arr)

Sum: 6


In [10]:
a1 = np.array([[1,2,3],[4,5,6]] ,dtype = np.float64)
Trans_arr = a1.T
print("Transpose of array")
print(Trans_arr)

Transpose of array
[[1. 4.]
 [2. 5.]
 [3. 6.]]


In [11]:
#indexing and slicing
a1 = np.array([1,2,3,4,5,6,7])
print(a1[3])

4


In [5]:
a1 = np.array((10,20,30,40,50))
print("array created using passed tuple:",a1)


array created using passed tuple: [10 20 30 40 50]


In [13]:
x = np.array([1,2])
print(x.dtype)

int64


In [14]:
x = np.array([1.0,2.0])
print("\n float datatype:")
print(x.dtype)


 float datatype:
float64


In [7]:
x = np.array([1,2],dtype = no.int64)
print("\n Forcing a datatype:")
print(x.dtype)

NameError: name 'no' is not defined

In [18]:
#shape
a1 = np.array([[1,2,3],[4,5,6]])
print(a1.shape)

(2, 3)


In [3]:
#reshape
import numpy as np
a1 = np.array([1,2,3,4,5,6,7,8])
print(a1.shape)
re_a1 = a1.reshape(4,2)
print(re_a1.shape)
print(re_a1)

(8,)
(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
a1= np.array([1,2,3,4,5,6])
re_a1= a1.reshape(2, -1)
print(re_a1)
print()
re_a1 = a1.reshape(-1)
print(re_a1)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [21]:
#Boolean array
a1 = np.array([1,0,1,0,0,0,1,0])
print(f"Original array:{a1}")
bool_a1 = np.array(a1, dtype='bool')
print(f"Boolean array: {bool_a1}")

Original array:[1 0 1 0 0 0 1 0]
Boolean array: [ True False  True False False False  True False]


In [23]:
a1 = np.array([5, None ,1,25,-10,0,'A'])
print(f"Original array:{a1}")
bool_a1 = np.array(a1, dtype = 'bool')
print(f"Bolean array:{bool_a1}")


Original array:[5 None 1 25 -10 0 'A']
Bolean array:[ True False  True  True  True False  True]


In [ ]:
a1 =

In [24]:
a1 = np.array([1,2,3,4,5])
gt3 = a1 > 3
lte2 = a1 <=2
et4 = a1==4
print(gt3)
print(lte2)
print(et4)

 

[False False False  True  True]
[ True  True False False False]
[False False False  True False]


In [25]:
a1 = np.array([1,2,3,4,5])
selected_elements = a1[gt3]
print(selected_elements)

[4 5]


In [26]:
combined_elements = (a1>2) & (a1<5)
print(combined_elements)

[False False  True  True False]


In [27]:
a1[a1>3] = 0
print(a1)

[1 2 3 0 0]
